/**
 * q7's recorded artefact: what `loadContent()` lets through today.
 *
 * Generated, not hand-written — regenerate with
 * `Q7_RECORD=1 npx vitest run tests/q7-data-fuzz.test.ts` and paste the three
 * blocks it prints. Do **not** edit an entry to make a red run green: an entry
 * appearing here means the loader accepts data it should refuse, so the fix
 * belongs in `src/sim/content.ts` and the deletion follows the fix.
 *
 * Three records, three jobs:
 *
 *   - `ACCEPTED` — canonical field path -> the mutation families the loader took
 *     without complaint. `tests/q7-data-fuzz.test.ts` asserts the census is a
 *     subset of this (a *new* hole goes red) and that nothing here has since
 *     been closed (a *stale* entry goes red).
 *   - `INEFFECTIVE` — the census cases whose mutation could not move the value:
 *     a field authored as 0 has no `zero` mutation, an empty array has no
 *     element to drop. Pinned exactly, so a family that quietly went inert
 *     cannot hide inside it.
 *   - `REF_VERDICTS` — canonical string path -> how its rows scored under a
 *     garbage rename. `checked` = every row is cross-checked by another file,
 *     `open` = no row is, `partial` = some are and some are not, which is the
 *     one-directional-integrity finding (E1).
 *
 * Recorded 2026-08-28 (fb005 QA fix) against the same 5,860 effective
 * mutations; 3,783 rejected, 2,077 accepted — down from 3,775/2,085 earlier
 * the same day: the six `damagetypes.types[]`/`statuses.frost`/
 * `statuses.frozen` `color`/`colorblindColor` fields and the two top-level
 * `executeColor`/`colorblindExecuteColor` fields moved from `str.optional()`
 * to a `hexColor` (`z.string().min(1)`) schema, closing a QA-filed bug where
 * an authored `color: ""` silently bypassed the documented white fallback
 * (`??` only guards `null`/`undefined`, not `""`) instead of behaving like an
 * unset field. Eight `empty-string` mutations move from ACCEPTED to
 * rejected, one per field — no other family changes and no new fields.
 * ACCEPTED updated in place, INEFFECTIVE and REF_VERDICTS unchanged.
 *
 * Recorded 2026-08-28 (fb005) against 5,860 effective mutations; 3,775
 * rejected, 2,085 accepted — up from 5,769/3,716/2,053 the same day, pre-item:
 * nine fields added (`color`/`colorblindColor` on every `damagetypes.types[]`
 * row and on `statuses.frost`/`statuses.frozen`, plus top-level
 * `executeColor`/`colorblindExecuteColor`/`executeFontScale` — the fb005
 * floating-damage-number style mapping, all optional with a neutral-fallback
 * reader per CLAUDE.md's architecture rule 4), 32 new accepted mutations, the
 * same optional-with-a-`??`-fallback shape every other field in this pattern
 * already gets. One real hole closed, not opened: `damagetypes.types |
 * dupe-element` was previously ACCEPTED (a duplicated damage-type row loaded
 * silently) and is now rejected, because `validateDamageStyleColors`
 * (content.ts, called from `loadContent`) throws on the duplicate's now-
 * identical color — the same distinctness rule fb005 added to satisfy "each
 * damage type visibly differs" catches a pre-existing referential gap as a
 * side effect. ACCEPTED updated in place, INEFFECTIVE and REF_VERDICTS
 * unchanged.
 *
 * Recorded 2026-08-27 (Q120 ORDER 1) against 5,769 effective mutations; 3,716
 * rejected, 2,053 accepted — up from 5,758/3,711/2,047 the same day, pre-order:
 * one field added (`classes.classes[].active2.totemTauntTickSeconds`, the
 * Recall Totem taunt-tag decay window this order made data-driven per
 * CLAUDE.md's architecture rule 4), six new accepted mutations (the same
 * shape every other optional-with-a-`??`-fallback field already gets — see
 * `spawns.budgetGrowthPerVsWave` two entries below), ACCEPTED updated in
 * place, INEFFECTIVE and REF_VERDICTS unchanged. Not itself a new hole this
 * order is obligated to close: it is one more instance of the pre-existing,
 * already-filed gap b013 covers (numeric `/data` fields with no range guard),
 * not a regression this item introduced deliberately unguarded.
 *
 * Recorded 2026-08-27 (p8a) against 5,758 effective mutations; 3,711 rejected,
 * 2,047 accepted — up from 5,747/3,706/2,041 the same day, pre-p8a: one field
 * added (`spawns.budgetGrowthPerVsWave`), six new accepted mutations, ACCEPTED
 * updated in place, INEFFECTIVE and REF_VERDICTS unchanged. First recorded
 * 2026-08-26 against the pre-merge roster (with `weapons.json`, before
 * `cores.json` and P6's eleven-class `classes.json`); this recording replaces
 * it wholesale after the merge. See BACKLOG-QUALITY.md's Log for the write-ups
 * E1-E7.
 */
import type { RefVerdict } from '../tools/fuzz-data';

/** Canonical field path -> mutation families `loadContent()` accepts for it. */
export const ACCEPTED: Readonly<Record<string, readonly string[]>> = {
  'affinity.affinities': ['empty-array', 'drop-element', 'dupe-element'],
  'affinity.affinities[].bonus': ['negative', 'zero', 'infinite', 'fractional'],
  'affinity.affinities[].perk': ['to-string', 'empty-string'],
  'affinity.affinities[].towers': ['empty-array', 'drop-element', 'dupe-element'],
  'boons.boons': ['empty-array', 'drop-element', 'dupe-element'],
  'boons.boons[].desc': ['to-string', 'empty-string'],
  'boons.boons[].key': ['to-string', 'empty-string'],
  'boons.boons[].maxRank': ['negative', 'zero', 'infinite', 'fractional'],
  'boons.boons[].name': ['to-string', 'empty-string'],
  'boons.boons[].perRank': ['negative', 'zero', 'infinite', 'fractional'],
  'boons.boons[].stat': ['to-string', 'empty-string'],
  'boons.rerollsPerLevel': ['negative', 'zero', 'infinite', 'fractional'],
  // fb015 (§7): dropping a class row can drop 'swordsman', which
  // equipment.json's classFallback rows (Sleeve Sword, Swordsman Armor,
  // Swordsman Shoes) all reference — `loadContent`'s new equipment
  // cross-file check now rejects that outright, closing the 'drop-element'
  // hole this used to have (q7's own "records no hole that has since been
  // closed" tripwire).
  'classes.classes': ['dupe-element'],
  'classes.classes[].active.cooldownSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active.damage': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active.dayUse': ['to-string', 'empty-string'],
  'classes.classes[].active.name': ['to-string', 'empty-string'],
  'classes.classes[].active.nightUse': ['to-string', 'empty-string'],
  'classes.classes[].active.radius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active.slow': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active.slowDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active1.burnDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active1.burnDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active1.chainCap': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.chainCount': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.chainGrowth': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.chargeCapSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.compoundPerSecond': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.cooldownSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.damage': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.groundDurationSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.knockback': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.minDamage': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.minRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.moveMulWhileCharging': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.name': ['to-string', 'empty-string'],
  'classes.classes[].active1.overclockAtkSpdMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.overclockSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.pierceCap': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.radius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.repairFraction': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.summonCap': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.summonDurationSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.summonRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.summonStatMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.tauntDurationSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.titheDamageMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active1.titheHpFraction': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.auraAtkSpdMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.cooldownSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.damage': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.dashRange': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.dashWidth': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.groundDurationSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.healPerEnemy': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.name': ['to-string', 'empty-string'],
  'classes.classes[].active2.overloadExtraChains': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.overloadSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.pactAtkSpdMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.pactDamageMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.pactDrainPerSecond': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.pylonDps': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.pylonInterval': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.pylonRange': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.radius': ['negative', 'infinite', 'fractional'],
  'classes.classes[].active2.summonCap': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.summonDurationSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.summonStatMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.totemDurationSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.totemTauntTickSeconds': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active2.trailSegments': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.volleyShots': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.wallSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active2.wrathDamageMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].basicAttack.aoe': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].basicAttack.dps': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].basicAttack.interval': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].basicAttack.range': ['negative', 'zero', 'infinite', 'fractional'],
  // fb015: retyping/emptying a class's own `key` can rename 'swordsman' away
  // (the one class equipment.json's classFallback rows target), which the
  // new equipment cross-file check now rejects — same closed hole as
  // `classes.classes` | drop-element above, see its comment.
  'classes.classes[].manualAttack.dps': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].manualAttack.interval': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].manualAttack.name': ['to-string', 'empty-string'],
  'classes.classes[].manualAttack.range': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].mods.buildRange': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.burnDamage': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.burnSpread': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.chilledDamageTaken': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.slowPotency': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.towerCost': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].moveSpeedBonus': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].name': ['to-string', 'empty-string'],
  'classes.classes[].passive.corpseSeconds': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].passive.description': ['to-string', 'empty-string'],
  'classes.classes[].passive.flameDps': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.flameRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.freezeHits': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].passive.frenzyTdMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.frenzyVsMul': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.kind': ['drop-key', 'rename-key'],
  'classes.classes[].passive.mods': ['drop-key', 'rename-key'],
  'classes.classes[].passive.mods.buildRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].passive.mods.leech': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].passive.mods.towerCost': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].passive.name': ['to-string', 'empty-string'],
  'classes.classes[].passive.shatterDamage': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.shatterRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.stanceArmor': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].passive.stanceSeconds': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].passive.wrathFraction': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].towerPassive.description': ['to-string', 'empty-string'],
  'classes.classes[].towerPassive.mods': ['drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.area': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerAttackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerDamageVsBurning': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerDamageVsChilled': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerDefenseBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerExtraElectricPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerLowHpDamageBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerPoisonDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.mods.towerRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].towerPassive.name': ['to-string', 'empty-string'],
  'classes.classes[].trait': ['to-string', 'empty-string'],
  'classes.classes[].unlockQuest': ['to-string'],
  'classes.classes[].unlockedByDefault': ['flip-bool'],
  'cores.cores[].baseHp': ['infinite', 'fractional'],
  'cores.cores[].effects': ['drop-key'],
  'cores.cores[].effects.corpseExecuteInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.corpseExplodeRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.corpseStoreRatio': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.devourCooldown': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.devourCoreHeal': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.devourEliteDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.devourRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.missingHpBuffCap': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.missingHpBuffPerPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.overhealGoldRatio': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.poisonBulletDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.poisonStacksPerBullet': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.poisonVolleyCap': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.poisonVolleyInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.tdSlowPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.tdSlowRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.towerLifestealPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.vsLifestealPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.vsSpeedPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].effects.vsXpGainPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].key': ['to-string', 'empty-string'],
  'cores.cores[].name': ['to-string', 'empty-string'],
  'cores.cores[].unlockCondition': ['to-string'],
  'cores.cores[].upgrade.desc': ['to-string', 'empty-string'],
  'cores.cores[].upgrade.stepCost': ['infinite', 'fractional'],
  'cores.cores[].upgrade.steps': ['empty-array', 'drop-element', 'drop-key'],
  'cores.cores[].upgrade.steps[].autoFireInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].coreHpBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].decayMult': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].decayRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].devourCooldownReduction': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].devourRangeBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].executeExplode': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].goldPerSecond': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].healingReceivedPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].hpRegenPerSecond': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].overhealGoldRatio': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].storeRatio': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].towerLifestealBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'cores.cores[].upgrade.steps[].towerOverhealConverts': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'damagetypes.colorblindExecuteColor': ['to-string', 'drop-key', 'rename-key'],
  'damagetypes.executeColor': ['to-string', 'drop-key', 'rename-key'],
  'damagetypes.executeFontScale': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'damagetypes.statuses.frost.attackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.statuses.frost.color': ['to-string', 'drop-key'],
  'damagetypes.statuses.frost.colorblindColor': ['to-string', 'drop-key'],
  'damagetypes.statuses.frost.desc': ['to-string', 'empty-string'],
  'damagetypes.statuses.frost.duration': ['negative', 'zero', 'infinite', 'fractional'],
  'damagetypes.statuses.frost.moveSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.statuses.frozen.color': ['to-string', 'drop-key'],
  'damagetypes.statuses.frozen.colorblindColor': ['to-string', 'drop-key'],
  'damagetypes.statuses.frozen.damageTaken': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.statuses.frozen.desc': ['to-string', 'empty-string'],
  'damagetypes.statuses.frozen.duration': ['negative', 'zero', 'infinite', 'fractional'],
  'damagetypes.types[].armorShredPerSecond': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.types[].color': ['to-string', 'drop-key'],
  'damagetypes.types[].colorblindColor': ['to-string', 'drop-key'],
  'damagetypes.types[].desc': ['to-string', 'empty-string'],
  'damagetypes.types[].dps': ['negative', 'zero', 'infinite', 'fractional'],
  'damagetypes.types[].duration': ['infinite', 'fractional'],
  'damagetypes.types[].ignoresArmor': ['flip-bool'],
  'damagetypes.types[].name': ['to-string', 'empty-string'],
  'damagetypes.types[].radius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.types[].ratio': ['negative', 'zero', 'infinite', 'fractional'],
  'dev.completeAllQuests': ['flip-bool'],
  'dev.devMode': ['flip-bool'],
  'dev.fillStash': ['flip-bool'],
  'dev.skillPoints': ['zero'],
  'dev.unlockAllClasses': ['flip-bool'],
  'dev.unlockAllCores': ['flip-bool'],
  'dev.unlockAllTiers': ['flip-bool'],
  'enemies.enemies': ['dupe-element'],
  'enemies.enemies[].attackDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].attackInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].attackRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].bounty': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].buffPower': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].buffRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].buffSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeCooldown': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeWindup': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].coreDamage': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].explodeDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].explodeRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].flatReduction': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].frontReduction': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].gem': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].healRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].healRate': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].hp': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].id': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].name': ['to-string', 'empty-string'],
  'enemies.enemies[].packSize': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].phaseDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].phasePeriod': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].radius': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].speed': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].splitCount': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].splitInto': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].stompDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].stompInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].stompRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].structureDamageMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].trailDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].trailRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].traits[]': ['to-string', 'empty-string'],
  // fb015 (§7): nothing else references an equipment item by index or count,
  // so dropping/duplicating/emptying `items` is accepted, same as
  // `modifiers.modifiers` below. `slots` duplicating is likewise harmless
  // (the loader reads it into a `Set`); dropping/emptying it is *not*
  // accepted — it desyncs from every item's own `.slot` and is rejected,
  // the same reasoning `classes.classes | drop-element` lost above.
  'equipment.items': ['empty-array', 'drop-element', 'dupe-element'],
  'equipment.items[].classFallback': ['drop-key'], // optional; absent is valid
  'equipment.items[].classFallback.mods.attackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].classFallback.mods.moveSpeedPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].desc': ['to-string', 'empty-string'],
  'equipment.items[].effectKey': ['drop-key'], // defaults to 'none'
  'equipment.items[].key': ['to-string', 'empty-string'],
  'equipment.items[].mods': ['drop-key'], // defaults to {}
  'equipment.items[].mods.area': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.armor': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.atkFlat': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.attackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.bleedLifesteal': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.charRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.hpRegen': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.leech': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.maxHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.moveSpeedPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.towerAtkFlat': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.towerCost': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.towerRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].mods.xpGain': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'equipment.items[].name': ['to-string', 'empty-string'],
  'equipment.slots': ['dupe-element'],
  'modifiers.modifiers': ['empty-array', 'drop-element', 'dupe-element'],
  'modifiers.modifiers[].desc': ['to-string', 'empty-string'],
  'modifiers.modifiers[].effect.bossHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.buildPhase': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.coreHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.eliteMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.enemyHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.enemySpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.extraGates': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.extraWaves': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.ghostWeightMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.pickupMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.residualMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.riftMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].key': ['to-string', 'empty-string'],
  'modifiers.modifiers[].name': ['to-string', 'empty-string'],
  'modifiers.modifiers[].rewardBonus': ['negative', 'zero', 'infinite', 'fractional'],
  'modifiers.tierRewardPerStep': ['negative', 'zero', 'infinite', 'fractional'],
  'quests.quests': ['empty-array', 'drop-element', 'dupe-element'],
  'quests.quests[].desc': ['to-string', 'empty-string'],
  'quests.quests[].key': ['to-string', 'empty-string'],
  'quests.quests[].metric': ['to-string', 'empty-string'],
  'quests.quests[].name': ['to-string', 'empty-string'],
  'quests.quests[].reward.kind': ['to-string', 'empty-string'],
  'quests.quests[].reward.value': ['to-string', 'empty-string'],
  'quests.quests[].target': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.affixes': ['empty-array', 'drop-element', 'dupe-element'],
  'relics.affixes[].key': ['to-string', 'empty-string'],
  'relics.affixes[].max': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.affixes[].min': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.affixes[].name': ['to-string', 'empty-string'],
  'relics.affixes[].pct': ['flip-bool'],
  'relics.affixes[].stat': ['to-string', 'empty-string'],
  'relics.dropRates.bossRelic': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'relics.dropRates.eliteRelic': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'relics.dropRates.waveRelic': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'relics.implicits.charm': ['drop-key', 'rename-key'],
  'relics.implicits.charm.stat': ['to-string', 'empty-string'],
  'relics.implicits.charm.value': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.implicits.plate': ['drop-key', 'rename-key'],
  'relics.implicits.plate.stat': ['to-string', 'empty-string'],
  'relics.implicits.plate.value': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.implicits.sigil': ['drop-key', 'rename-key'],
  'relics.implicits.sigil.stat': ['to-string', 'empty-string'],
  'relics.implicits.sigil.value': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.luckRarityShift': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.rarities': ['empty-array', 'drop-element', 'dupe-element'],
  'relics.rarities[].key': ['to-string', 'empty-string'],
  'relics.rarities[].maxAffixes': ['negative', 'infinite', 'fractional'],
  'relics.rarities[].minAffixes': ['negative', 'infinite', 'fractional'],
  'relics.rarities[].name': ['to-string', 'empty-string'],
  'relics.rarities[].weight': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.slots': ['empty-array', 'drop-element', 'dupe-element'],
  'relics.slots[]': ['to-string', 'empty-string'],
  'relics.stashSlots': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.actIICarry': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.aliveCap': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.bossTimeSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.budgetBase': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.budgetGrowthPerMinute': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.budgetGrowthPerVsWave': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'spawns.burrowSurfaceDistance': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.contactInterval': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.contactPadding': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.bomber': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.bulwark': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.burrower': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.charger': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.cinderling': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.colossus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.costs.frostkin': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.gale_imp': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.herald': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.costs.husk': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.mender': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.shellback': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.spitter': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.splitling': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.sprinter': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.swarm_rat': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.warlock': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.wraith': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.directorIntervalSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.eliteIntervalSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.eliteWeights.colossus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'spawns.eliteWeights.herald': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'spawns.gemCap': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.gemLifetimeSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.hpOverlay': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.hpScalePerMinute': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.leakBudgetMultiplier': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.riftBudgetMultiplier': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.riftTimes': ['empty-array', 'drop-element', 'dupe-element'],
  'spawns.riftTimes[]': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.spawnDistance': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.speedOverlay': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.warmupSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.warmupStart': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.weightsByMinute': ['empty-array', 'drop-element', 'dupe-element'],
  'spawns.weightsByMinute[].minute': ['negative', 'infinite', 'fractional'],
  'spawns.weightsByMinute[].weights.bomber': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.bulwark': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.burrower': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.charger': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.cinderling': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.frostkin': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.gale_imp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.husk': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.mender': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.shellback': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.spitter': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.splitling': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.sprinter': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.swarm_rat': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.warlock': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.wraith': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'towers.aoeFalloff': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.aoeFalloffFloor': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.aoeFullTargets': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.breach.base': ['zero', 'infinite', 'fractional'],
  'towers.breach.perEhp': ['zero', 'infinite', 'fractional'],
  'towers.buildRange': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.defenseBands.low': ['rename-key'],
  'towers.defenseBands.medium': ['rename-key'],
  'towers.defenseBands.none': ['rename-key'],
  'towers.milestoneStepsSkipStats': ['flip-bool'],
  'towers.pierceFalloff': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.pierceFalloffFloor': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.sellRefund': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers': ['dupe-element'],
  'towers.towers[].attack.aoe': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.burn.dps': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.burn.duration': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.chainRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.chains': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.coneHalfAngle': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.damage': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.damageRatio.electric': ['infinite', 'fractional'],
  'towers.towers[].attack.damageRatio.normal': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.towers[].attack.damageRatio.poison': ['zero', 'infinite', 'drop-key'],
  'towers.towers[].attack.interval': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.minRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.pierce': ['negative', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.projectileSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.projectiles': ['drop-key', 'rename-key'],
  'towers.towers[].attack.range': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.slow': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.slowDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].blocks': ['flip-bool'],
  'towers.towers[].buffAura': ['drop-key'],
  'towers.towers[].buffAura.attackSpeed': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].buffAura.radius': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].cost': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].desc': ['to-string', 'empty-string'],
  'towers.towers[].economy': ['drop-key'],
  'towers.towers[].economy.goldPerWavePerTier': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].hp': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].id': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].name': ['to-string', 'empty-string'],
  'towers.towers[].passive': ['drop-key'],
  'towers.towers[].passive.attackSpeedPer': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].passive.cap': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].terrain.armorCap': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.armorPerWall': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.blocks': ['flip-bool'],
  'towers.towers[].terrain.gemInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.gemMax': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.gemValue': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.kind': ['to-string', 'empty-string'],
  'towers.towers[].terrain.linkRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.maxLinks': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.wardenAttackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.wardenRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].upgrades.note': ['to-string', 'empty-string', 'drop-key'],
  'towers.towers[].upgrades.specials': ['drop-key'],
  'towers.towers[].upgrades.specials[].mul': ['infinite', 'fractional'],
  'towers.towers[].upgrades.specials[].note': ['to-string', 'empty-string', 'drop-key'],
  'towers.towers[].upgrades.specials[].ratio.normal': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.towers[].upgrades.specials[].ratio.poison': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.towers[].upgrades.specials[].seconds': ['infinite', 'fractional'],
  'towers.towers[].vsSpecial.damage': ['zero', 'infinite', 'fractional'],
  'towers.towers[].vsSpecial.interval': ['infinite', 'fractional'],
  'towers.towers[].vsSpecial.radius': ['infinite', 'fractional'],
  'towers.towers[].vsSpecial.ratio': ['infinite', 'fractional'],
  'towers.upgradeStepMul': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.emberBase': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.maxAccountLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.nodes': ['empty-array', 'dupe-element'],
  'tree.nodes[].angle': ['to-null', 'to-string', 'to-bool', 'to-array', 'to-object', 'negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].branch': ['to-string', 'empty-string'],
  'tree.nodes[].desc': ['to-string', 'empty-string'],
  'tree.nodes[].key': ['to-string', 'empty-string', 'drop-key', 'rename-key'],
  'tree.nodes[].links': ['empty-array', 'drop-element', 'dupe-element'],
  'tree.nodes[].links[]': ['zero'],
  'tree.nodes[].name': ['to-string', 'empty-string'],
  'tree.nodes[].ring': ['to-null', 'to-string', 'to-bool', 'to-array', 'to-object', 'negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.area': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.armor': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.attackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.beaconRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.buildRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.coreHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.dashCharges': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.emberFind': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.goldFind': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.goldPerKill': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.hpRegen': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.lastStandSundering': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.leech': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.luck': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.maxHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.maxHpPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.modRewardBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.moveSpeedPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.pickupPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.power': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.relicFind': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.residualPotency': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.sproutGold': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.teslaLinks': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.towerCost': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.towerDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.towerRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.wallHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].x': ['negative', 'infinite', 'fractional'],
  'tree.nodes[].y': ['negative', 'infinite', 'fractional'],
  'tree.pointsPerLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.respecCostPerNode': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.startingEmber': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.armor': ['negative', 'infinite', 'fractional'],
  'warden.armorCap': ['zero', 'fractional'],
  'warden.armorFloor': ['negative', 'zero', 'fractional'],
  'warden.cdrCap': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.dashCooldown': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.dashDistance': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.dashIFrames': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.heartstoneHeal': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.heartstoneRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.hpRegen': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.manualAttackDisabledInActII': ['flip-bool'],
  'warden.maxHp': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.moveSpeed': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.outOfCombatSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.pickupRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.buildPhaseSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.coreHp': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.earlyCallGoldPerSecond': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.eliteMulByCycle': ['drop-key', 'rename-key'],
  'waves.eliteMulByCycle.2': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'waves.enemyStructureDpsFactor': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.hpScalePerWave': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.maxStackedWaves': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.nightMinuteOffsetPerCycle': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'waves.spawnIntervalSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.startGold': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.tdWavesPerVsWave': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.vsWaveSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waveClearBase': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waveClearPerWave': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waves': ['empty-array', 'drop-element', 'dupe-element'],
  'waves.waves[].groups': ['empty-array', 'drop-element', 'dupe-element'],
  'waves.waves[].groups[].perGate': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waves[].groups[].total': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waves[].wave': ['negative', 'zero', 'infinite', 'fractional'],
};

/** Census cases whose mutation cannot move the authored value. */
export const INEFFECTIVE: readonly string[] = [
  'classes.classes[].active2.radius | zero',
  'classes.classes[].mods.towerCost | zero',
  'classes.classes[].mods.buildRange | zero',
  'classes.classes[].mods.burnDamage | zero',
  'classes.classes[].mods.burnSpread | zero',
  'enemies.enemies[].traits | empty-array',
  'enemies.enemies[].traits | drop-element',
  'enemies.enemies[].traits | dupe-element',
  'relics.rarities[].minAffixes | zero',
  'relics.rarities[].maxAffixes | zero',
  'spawns.weightsByMinute[].minute | zero',
  'towers.defenseBands.none | zero',
  'towers.towers[].defense | zero',
  'towers.towers[].upgrades.count | zero',
  'towers.towers[].upgrades.stepCost | zero',
  'towers.towers[].upgrades.specials | empty-array',
  'towers.towers[].upgrades.specials | drop-element',
  'towers.towers[].upgrades.specials | dupe-element',
  'towers.towers[].attack.pierce | zero',
  'tree.nodes[].id | zero',
  'tree.nodes[].x | zero',
  'tree.nodes[].y | zero',
  'tree.nodes[].ring | zero',
  'warden.armor | zero',
];

/** Canonical string path -> how its rows scored under a garbage rename. */
export const REF_VERDICTS: Readonly<Record<string, RefVerdict>> = {
  'affinity.affinities[].classKey': 'checked',
  'affinity.affinities[].perk': 'open',
  'affinity.affinities[].towers[]': 'checked',
  'boons.boons[].desc': 'open',
  'boons.boons[].key': 'open',
  'boons.boons[].name': 'open',
  'boons.boons[].stat': 'open',
  'classes.classes[].active.dayUse': 'open',
  'classes.classes[].active.kind': 'checked',
  'classes.classes[].active.name': 'open',
  'classes.classes[].active.nightUse': 'open',
  'classes.classes[].active1.kind': 'checked',
  'classes.classes[].active1.name': 'open',
  'classes.classes[].active2.kind': 'checked',
  'classes.classes[].active2.name': 'open',
  'classes.classes[].active2.towerKey': 'checked',
  'classes.classes[].key': 'partial',
  'classes.classes[].manualAttack.name': 'open',
  'classes.classes[].name': 'open',
  'classes.classes[].passive.description': 'open',
  'classes.classes[].passive.kind': 'checked',
  'classes.classes[].passive.name': 'open',
  'classes.classes[].towerPassive.description': 'open',
  'classes.classes[].towerPassive.name': 'open',
  'classes.classes[].trait': 'open',
  'classes.classes[].unlockQuest': 'open',
  'cores.cores[].key': 'open',
  'cores.cores[].name': 'open',
  'cores.cores[].unlockCondition': 'open',
  'cores.cores[].upgrade.desc': 'open',
  'damagetypes.colorblindExecuteColor': 'open',
  'damagetypes.executeColor': 'open',
  'damagetypes.statuses.frost.color': 'open',
  'damagetypes.statuses.frost.colorblindColor': 'open',
  'damagetypes.statuses.frost.desc': 'open',
  'damagetypes.statuses.frozen.color': 'open',
  'damagetypes.statuses.frozen.colorblindColor': 'open',
  'damagetypes.statuses.frozen.desc': 'open',
  'damagetypes.types[].color': 'open',
  'damagetypes.types[].colorblindColor': 'open',
  'damagetypes.types[].desc': 'open',
  'damagetypes.types[].effect': 'checked',
  'damagetypes.types[].key': 'partial',
  'damagetypes.types[].name': 'open',
  'damagetypes.types[].refresh': 'checked',
  'enemies.enemies[].grade': 'checked',
  'enemies.enemies[].key': 'partial',
  'enemies.enemies[].name': 'open',
  'enemies.enemies[].traits[]': 'open',
  // fb015 (§7): `slot`/`effectKey`/`classFallback.notClassKey` are all
  // cross-checked at load (`equipmentSlots.has`/zod enum/`classKeys.has`
  // respectively, content.ts) — a garbage rename of any of them, or of the
  // `slots[]` row it targets, is rejected. `key`/`name`/`desc` are display
  // text nothing else references, same as every other item table's own.
  'equipment.items[].classFallback.notClassKey': 'checked',
  'equipment.items[].desc': 'open',
  'equipment.items[].effectKey': 'checked',
  'equipment.items[].key': 'open',
  'equipment.items[].name': 'open',
  'equipment.items[].slot': 'checked',
  'equipment.slots[]': 'checked',
  'modifiers.modifiers[].desc': 'open',
  'modifiers.modifiers[].key': 'open',
  'modifiers.modifiers[].name': 'open',
  'quests.quests[].compare': 'checked',
  'quests.quests[].desc': 'open',
  'quests.quests[].key': 'open',
  'quests.quests[].metric': 'open',
  'quests.quests[].name': 'open',
  'quests.quests[].reward.kind': 'open',
  'quests.quests[].reward.value': 'open',
  'relics.affixes[].key': 'open',
  'relics.affixes[].name': 'open',
  'relics.affixes[].stat': 'open',
  'relics.implicits.charm.stat': 'open',
  'relics.implicits.plate.stat': 'open',
  'relics.implicits.sigil.stat': 'open',
  'relics.rarities[].key': 'open',
  'relics.rarities[].name': 'open',
  'relics.slots[]': 'open',
  'towers.towers[].attack.kind': 'checked',
  'towers.towers[].desc': 'open',
  'towers.towers[].key': 'partial',
  'towers.towers[].name': 'open',
  'towers.towers[].terrain.kind': 'open',
  'towers.towers[].upgrades.note': 'open',
  'towers.towers[].upgrades.specials[].key': 'checked',
  'towers.towers[].upgrades.specials[].note': 'open',
  'towers.towers[].upgrades.specials[].type': 'checked',
  'towers.towers[].vsSpecial.kind': 'checked',
  'tree.nodes[].branch': 'open',
  'tree.nodes[].desc': 'open',
  'tree.nodes[].key': 'open',
  'tree.nodes[].kind': 'checked',
  'tree.nodes[].name': 'open',
  'waves.waves[].groups[].enemy': 'checked',
};
