/**
 * q7's recorded artefact: what `loadContent()` lets through today.
 *
 * Generated, not hand-written — regenerate with
 * `Q7_RECORD=1 npx vitest run tests/q7-data-fuzz.test.ts` and paste the three
 * blocks it prints. Do **not** edit an entry to make a red run green: an entry
 * appearing here means the loader accepts data it should refuse, so the fix
 * belongs in `src/sim/content.ts` and the deletion follows the fix.
 *
 * Three records, three jobs:
 *
 *   - `ACCEPTED` — canonical field path -> the mutation families the loader took
 *     without complaint. `tests/q7-data-fuzz.test.ts` asserts the census is a
 *     subset of this (a *new* hole goes red) and that nothing here has since
 *     been closed (a *stale* entry goes red).
 *   - `INEFFECTIVE` — the census cases whose mutation could not move the value:
 *     a field authored as 0 has no `zero` mutation, an empty array has no
 *     element to drop. Pinned exactly, so a family that quietly went inert
 *     cannot hide inside it.
 *   - `REF_VERDICTS` — canonical string path -> how its rows scored under a
 *     garbage rename. `checked` = every row is cross-checked by another file,
 *     `open` = no row is, `partial` = some are and some are not, which is the
 *     one-directional-integrity finding (E1).
 *
 * Recorded 2026-08-26 against 4,775 effective mutations; 3,077 rejected, 1,698
 * accepted. See BACKLOG-QUALITY.md's Log for the write-ups E1-E7.
 */
import type { RefVerdict } from '../tools/fuzz-data';

/** Canonical field path -> mutation families `loadContent()` accepts for it. */
export const ACCEPTED: Readonly<Record<string, readonly string[]>> = {
  'affinity.affinities': ['empty-array', 'drop-element', 'dupe-element'],
  'affinity.affinities[].bonus': ['negative', 'zero', 'infinite', 'fractional'],
  'affinity.affinities[].perk': ['to-string', 'empty-string'],
  'affinity.affinities[].towers': ['empty-array', 'drop-element', 'dupe-element'],
  'boons.boons': ['dupe-element'],
  'boons.boons[].desc': ['to-string', 'empty-string'],
  'boons.boons[].maxRank': ['negative', 'zero', 'infinite', 'fractional'],
  'boons.boons[].name': ['to-string', 'empty-string'],
  'boons.boons[].perRank': ['negative', 'zero', 'infinite', 'fractional'],
  'boons.boons[].stat': ['to-string', 'empty-string'],
  'boons.rerollsPerLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes': ['dupe-element'],
  'classes.classes[].active.burnDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active.burnDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active.cooldownSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active.damage': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active.dayUse': ['to-string', 'empty-string'],
  'classes.classes[].active.name': ['to-string', 'empty-string'],
  'classes.classes[].active.nightUse': ['to-string', 'empty-string'],
  'classes.classes[].active.radius': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].active.slow': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].active.slowDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].manualAttack.dps': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].manualAttack.interval': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].manualAttack.name': ['to-string', 'empty-string'],
  'classes.classes[].manualAttack.range': ['negative', 'zero', 'infinite', 'fractional'],
  'classes.classes[].mods.buildRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.burnDamage': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.burnSpread': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.chilledDamageTaken': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.slowPotency': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].mods.towerCost': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'classes.classes[].name': ['to-string', 'empty-string'],
  'classes.classes[].passive.description': ['to-string', 'empty-string'],
  'classes.classes[].passive.name': ['to-string', 'empty-string'],
  'classes.classes[].trait': ['to-string', 'empty-string'],
  'classes.classes[].unlockQuest': ['to-string'],
  'classes.classes[].unlockedByDefault': ['flip-bool'],
  'damagetypes.statuses.frost.attackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.statuses.frost.desc': ['to-string', 'empty-string'],
  'damagetypes.statuses.frost.duration': ['negative', 'zero', 'infinite', 'fractional'],
  'damagetypes.statuses.frost.moveSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.statuses.frozen.damageTaken': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.statuses.frozen.desc': ['to-string', 'empty-string'],
  'damagetypes.statuses.frozen.duration': ['negative', 'zero', 'infinite', 'fractional'],
  'damagetypes.types': ['dupe-element'],
  'damagetypes.types[].armorShredPerSecond': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.types[].desc': ['to-string', 'empty-string'],
  'damagetypes.types[].dps': ['negative', 'zero', 'infinite', 'fractional'],
  'damagetypes.types[].duration': ['infinite', 'fractional'],
  'damagetypes.types[].ignoresArmor': ['flip-bool'],
  'damagetypes.types[].name': ['to-string', 'empty-string'],
  'damagetypes.types[].radius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'damagetypes.types[].ratio': ['negative', 'zero', 'infinite', 'fractional'],
  'dev.completeAllQuests': ['flip-bool'],
  'dev.devMode': ['flip-bool'],
  'dev.fillStash': ['flip-bool'],
  'dev.skillPoints': ['zero'],
  'dev.unlockAllClasses': ['flip-bool'],
  'dev.unlockAllTiers': ['flip-bool'],
  'enemies.enemies': ['dupe-element'],
  'enemies.enemies[].attackDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].attackInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].attackRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].bounty': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].buffPower': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].buffRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].buffSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeCooldown': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].chargeWindup': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].coreDamage': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].explodeDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].explodeRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].flatReduction': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].frontReduction': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].gem': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].healRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].healRate': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].hp': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].id': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].name': ['to-string', 'empty-string'],
  'enemies.enemies[].packSize': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].phaseDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].phasePeriod': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].radius': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].speed': ['negative', 'zero', 'infinite', 'fractional'],
  'enemies.enemies[].splitCount': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].splitInto': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].stompDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].stompInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].stompRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].structureDamageMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].trailDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].trailRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'enemies.enemies[].traits[]': ['to-string', 'empty-string'],
  'modifiers.modifiers': ['empty-array', 'drop-element', 'dupe-element'],
  'modifiers.modifiers[].desc': ['to-string', 'empty-string'],
  'modifiers.modifiers[].effect.bossHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.buildPhase': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.coreHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.eliteMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.enemyHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.enemySpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.extraGates': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.extraWaves': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.ghostWeightMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.pickupMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.residualMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].effect.riftMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'modifiers.modifiers[].key': ['to-string', 'empty-string'],
  'modifiers.modifiers[].name': ['to-string', 'empty-string'],
  'modifiers.modifiers[].rewardBonus': ['negative', 'zero', 'infinite', 'fractional'],
  'modifiers.tierRewardPerStep': ['negative', 'zero', 'infinite', 'fractional'],
  'quests.quests': ['empty-array', 'drop-element', 'dupe-element'],
  'quests.quests[].desc': ['to-string', 'empty-string'],
  'quests.quests[].key': ['to-string', 'empty-string'],
  'quests.quests[].metric': ['to-string', 'empty-string'],
  'quests.quests[].name': ['to-string', 'empty-string'],
  'quests.quests[].reward.kind': ['to-string', 'empty-string'],
  'quests.quests[].reward.value': ['to-string', 'empty-string'],
  'quests.quests[].target': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.affixes': ['empty-array', 'drop-element', 'dupe-element'],
  'relics.affixes[].key': ['to-string', 'empty-string'],
  'relics.affixes[].max': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.affixes[].min': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.affixes[].name': ['to-string', 'empty-string'],
  'relics.affixes[].pct': ['flip-bool'],
  'relics.affixes[].stat': ['to-string', 'empty-string'],
  'relics.dropRates.bossRelic': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'relics.dropRates.eliteRelic': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'relics.dropRates.waveRelic': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'relics.implicits.charm': ['drop-key', 'rename-key'],
  'relics.implicits.charm.stat': ['to-string', 'empty-string'],
  'relics.implicits.charm.value': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.implicits.plate': ['drop-key', 'rename-key'],
  'relics.implicits.plate.stat': ['to-string', 'empty-string'],
  'relics.implicits.plate.value': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.implicits.sigil': ['drop-key', 'rename-key'],
  'relics.implicits.sigil.stat': ['to-string', 'empty-string'],
  'relics.implicits.sigil.value': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.luckRarityShift': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.rarities': ['empty-array', 'drop-element', 'dupe-element'],
  'relics.rarities[].key': ['to-string', 'empty-string'],
  'relics.rarities[].maxAffixes': ['negative', 'infinite', 'fractional'],
  'relics.rarities[].minAffixes': ['negative', 'infinite', 'fractional'],
  'relics.rarities[].name': ['to-string', 'empty-string'],
  'relics.rarities[].weight': ['negative', 'zero', 'infinite', 'fractional'],
  'relics.slots': ['empty-array', 'drop-element', 'dupe-element'],
  'relics.slots[]': ['to-string', 'empty-string'],
  'relics.stashSlots': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.actIICarry': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.aliveCap': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.bossTimeSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.budgetBase': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.budgetGrowthPerMinute': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.burrowSurfaceDistance': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.contactInterval': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.contactPadding': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.bomber': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.bulwark': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.burrower': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.charger': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.cinderling': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.colossus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.costs.frostkin': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.gale_imp': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.herald': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.costs.husk': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.mender': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.shellback': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.spitter': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.splitling': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.sprinter': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.swarm_rat': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.warlock': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.costs.wraith': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.directorIntervalSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.eliteIntervalSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.eliteWeights.colossus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'spawns.eliteWeights.herald': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'spawns.gemCap': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.gemLifetimeSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.hpOverlay': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.hpScalePerMinute': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.leakBudgetMultiplier': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.riftBudgetMultiplier': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.riftTimes': ['empty-array', 'drop-element', 'dupe-element'],
  'spawns.riftTimes[]': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.spawnDistance': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.speedOverlay': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.warmupSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.warmupStart': ['negative', 'zero', 'infinite', 'fractional'],
  'spawns.weightsByMinute': ['empty-array', 'drop-element', 'dupe-element'],
  'spawns.weightsByMinute[].minute': ['negative', 'infinite', 'fractional'],
  'spawns.weightsByMinute[].weights.bomber': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.bulwark': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.burrower': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.charger': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.cinderling': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.frostkin': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.gale_imp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.husk': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.mender': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.shellback': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.spitter': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.splitling': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.sprinter': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.swarm_rat': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.warlock': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'spawns.weightsByMinute[].weights.wraith': ['negative', 'zero', 'infinite', 'fractional', 'drop-key'],
  'towers.buildRange': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.defenseBands.low': ['rename-key'],
  'towers.defenseBands.medium': ['rename-key'],
  'towers.defenseBands.none': ['rename-key'],
  'towers.milestoneStepsSkipStats': ['flip-bool'],
  'towers.rekindleCostMul': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.sellRefund': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers': ['drop-element', 'dupe-element'],
  'towers.towers[].attack.aoe': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.burn': ['drop-key', 'rename-key'],
  'towers.towers[].attack.burn.dps': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.burn.duration': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.chainRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.chains': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.coneHalfAngle': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.damage': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.damageRatio.electric': ['infinite', 'fractional'],
  'towers.towers[].attack.damageRatio.normal': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.towers[].attack.damageRatio.poison': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.towers[].attack.interval': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.minRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.pierce': ['negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.projectileSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.projectiles': ['drop-key', 'rename-key'],
  'towers.towers[].attack.range': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].attack.slow': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].attack.slowDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].blocks': ['flip-bool'],
  'towers.towers[].buffAura': ['drop-key'],
  'towers.towers[].buffAura.attackSpeed': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].buffAura.radius': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].cost': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].desc': ['to-string', 'empty-string'],
  'towers.towers[].economy': ['drop-key'],
  'towers.towers[].economy.goldPerWavePerTier': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].hp': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].id': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].key': ['to-string', 'empty-string'],
  'towers.towers[].name': ['to-string', 'empty-string'],
  'towers.towers[].passive': ['drop-key'],
  'towers.towers[].passive.attackSpeedPer': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].passive.cap': ['negative', 'zero', 'infinite', 'fractional'],
  'towers.towers[].terrain.armorCap': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.armorPerWall': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.auraDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.auraRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.auraType': ['drop-key', 'rename-key'],
  'towers.towers[].terrain.beamDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.blocks': ['flip-bool'],
  'towers.towers[].terrain.gemInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.gemMax': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.gemValue': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.kind': ['to-string', 'empty-string'],
  'towers.towers[].terrain.linkRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.maxLinks': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.slow': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.wardenAttackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].terrain.wardenRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'towers.towers[].upgrades.note': ['to-string', 'empty-string', 'drop-key'],
  'towers.towers[].upgrades.specials': ['drop-key'],
  'towers.towers[].upgrades.specials[].note': ['to-string', 'empty-string', 'drop-key'],
  'towers.towers[].upgrades.specials[].ratio.normal': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.towers[].upgrades.specials[].ratio.poison': ['zero', 'infinite', 'fractional', 'drop-key'],
  'towers.upgradeStepMul': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.emberBase': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.maxAccountLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.nodes': ['empty-array', 'dupe-element'],
  'tree.nodes[].angle': ['to-null', 'to-string', 'to-bool', 'to-array', 'to-object', 'negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].branch': ['to-string', 'empty-string'],
  'tree.nodes[].desc': ['to-string', 'empty-string'],
  'tree.nodes[].key': ['to-string', 'empty-string', 'drop-key', 'rename-key'],
  'tree.nodes[].links': ['empty-array', 'drop-element', 'dupe-element'],
  'tree.nodes[].links[]': ['zero'],
  'tree.nodes[].name': ['to-string', 'empty-string'],
  'tree.nodes[].ring': ['to-null', 'to-string', 'to-bool', 'to-array', 'to-object', 'negative', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.area': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.armor': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.attackSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.beaconRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.buildRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.coreHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.dashCharges': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.emberFind': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.goldFind': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.goldPerKill': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.hpRegen': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.lastStandSundering': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.leech': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.luck': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.maxHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.maxHpPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.modRewardBonus': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.moveSpeedPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.pickupPct': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.power': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.relicFind': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.residualPotency': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.sproutGold': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.startWeaponLevel': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.teslaLinks': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.towerCost': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.towerDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.towerRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.wallHp': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].stats.weaponSlots': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'tree.nodes[].x': ['negative', 'infinite', 'fractional'],
  'tree.nodes[].y': ['negative', 'infinite', 'fractional'],
  'tree.pointsPerLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.respecCostPerNode': ['negative', 'zero', 'infinite', 'fractional'],
  'tree.startingEmber': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.armor': ['negative', 'infinite', 'fractional'],
  'warden.armorCap': ['zero', 'fractional'],
  'warden.armorFloor': ['negative', 'zero', 'fractional'],
  'warden.cdrCap': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.dashCooldown': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.dashDistance': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.dashIFrames': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.heartstoneHeal': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.heartstoneRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.hpRegen': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.leechCapPerSecond': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.manualAttackDisabledInActII': ['flip-bool'],
  'warden.maxHp': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.moveSpeed': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.outOfCombatSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'warden.pickupRadius': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.buildPhaseSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.coreHp': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.earlyCallGoldPerSecond': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.eliteMulByCycle': ['drop-key', 'rename-key'],
  'waves.eliteMulByCycle.2': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'waves.enemyStructureDpsFactor': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.hpScalePerWave': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.nightMinuteOffsetPerCycle': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'waves.nightSecondsByCycle': ['empty-array', 'drop-element', 'dupe-element'],
  'waves.nightSecondsByCycle[]': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.spawnIntervalSeconds': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.startGold': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waveClearBase': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waveClearPerWave': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waveEndByCycle': ['empty-array', 'drop-element', 'dupe-element'],
  'waves.waveEndByCycle[]': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waves': ['empty-array', 'drop-element', 'dupe-element'],
  'waves.waves[].groups': ['empty-array', 'drop-element', 'dupe-element'],
  'waves.waves[].groups[].perGate': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waves[].groups[].total': ['negative', 'zero', 'infinite', 'fractional'],
  'waves.waves[].wave': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.aoeFalloff': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.aoeFalloffFloor': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.aoeFullTargets': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.awakenings': ['empty-array', 'drop-element', 'dupe-element'],
  'weapons.awakenings[].boonRank': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.awakenings[].desc': ['to-string', 'empty-string'],
  'weapons.awakenings[].effect.damageMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.extraChains': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.extraCount': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.intervalMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.radiusMul': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.ringDamage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.ringInterval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.ringOrbs': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.ringRadius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].effect.ringSpeed': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.awakenings[].key': ['to-string', 'empty-string'],
  'weapons.awakenings[].name': ['to-string', 'empty-string'],
  'weapons.inheritDamageCap': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.inheritDamagePerExtraTower': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.inheritMaxLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.maxLevel': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.pierceFalloff': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.pierceFalloffFloor': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.slots': ['negative', 'zero', 'infinite', 'fractional'],
  'weapons.weapons': ['drop-element', 'dupe-element'],
  'weapons.weapons[].desc': ['to-string', 'empty-string'],
  'weapons.weapons[].key': ['to-string', 'empty-string'],
  'weapons.weapons[].levels[].bolts': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].burnDps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].burnDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].chainRange': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].chains': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].count': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].damage': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].dps': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].duration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].halfAngle': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].interval': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].radius': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].range': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].slow': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].slowDuration': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].targets': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].levels[].width': ['negative', 'zero', 'infinite', 'fractional', 'drop-key', 'rename-key'],
  'weapons.weapons[].name': ['to-string', 'empty-string'],
  'weapons.weapons[].slotless': ['flip-bool', 'drop-key', 'rename-key'],
};

/** Census cases whose mutation cannot move the authored value. */
export const INEFFECTIVE: readonly string[] = [
  'classes.classes[].mods.burnDamage | zero',
  'classes.classes[].mods.burnSpread | zero',
  'classes.classes[].mods.slowPotency | zero',
  'classes.classes[].mods.chilledDamageTaken | zero',
  'enemies.enemies[].traits | empty-array',
  'enemies.enemies[].traits | drop-element',
  'enemies.enemies[].traits | dupe-element',
  'relics.rarities[].minAffixes | zero',
  'relics.rarities[].maxAffixes | zero',
  'spawns.weightsByMinute[].minute | zero',
  'towers.defenseBands.none | zero',
  'towers.towers[].defense | zero',
  'towers.towers[].upgrades.count | zero',
  'towers.towers[].upgrades.stepCost | zero',
  'towers.towers[].upgrades.specials | empty-array',
  'towers.towers[].upgrades.specials | drop-element',
  'towers.towers[].upgrades.specials | dupe-element',
  'towers.towers[].attack.pierce | zero',
  'tree.nodes[].id | zero',
  'tree.nodes[].x | zero',
  'tree.nodes[].y | zero',
  'tree.nodes[].ring | zero',
  'warden.armor | zero',
];

/** Canonical string path -> how its rows scored under a garbage rename. */
export const REF_VERDICTS: Readonly<Record<string, RefVerdict>> = {
  'affinity.affinities[].classKey': 'checked',
  'affinity.affinities[].perk': 'open',
  'affinity.affinities[].towers[]': 'checked',
  'boons.boons[].desc': 'open',
  'boons.boons[].key': 'partial',
  'boons.boons[].name': 'open',
  'boons.boons[].stat': 'open',
  'classes.classes[].active.dayUse': 'open',
  'classes.classes[].active.kind': 'checked',
  'classes.classes[].active.name': 'open',
  'classes.classes[].active.nightUse': 'open',
  'classes.classes[].key': 'checked',
  'classes.classes[].manualAttack.name': 'open',
  'classes.classes[].name': 'open',
  'classes.classes[].passive.description': 'open',
  'classes.classes[].passive.name': 'open',
  'classes.classes[].trait': 'open',
  'classes.classes[].unlockQuest': 'open',
  'damagetypes.statuses.frost.desc': 'open',
  'damagetypes.statuses.frozen.desc': 'open',
  'damagetypes.types[].desc': 'open',
  'damagetypes.types[].effect': 'checked',
  'damagetypes.types[].key': 'partial',
  'damagetypes.types[].name': 'open',
  'damagetypes.types[].refresh': 'checked',
  'enemies.enemies[].grade': 'checked',
  'enemies.enemies[].key': 'partial',
  'enemies.enemies[].name': 'open',
  'enemies.enemies[].traits[]': 'open',
  'modifiers.modifiers[].desc': 'open',
  'modifiers.modifiers[].key': 'open',
  'modifiers.modifiers[].name': 'open',
  'quests.quests[].compare': 'checked',
  'quests.quests[].desc': 'open',
  'quests.quests[].key': 'open',
  'quests.quests[].metric': 'open',
  'quests.quests[].name': 'open',
  'quests.quests[].reward.kind': 'open',
  'quests.quests[].reward.value': 'open',
  'relics.affixes[].key': 'open',
  'relics.affixes[].name': 'open',
  'relics.affixes[].stat': 'open',
  'relics.implicits.charm.stat': 'open',
  'relics.implicits.plate.stat': 'open',
  'relics.implicits.sigil.stat': 'open',
  'relics.rarities[].key': 'open',
  'relics.rarities[].name': 'open',
  'relics.slots[]': 'open',
  'towers.towers[].attack.kind': 'checked',
  'towers.towers[].desc': 'open',
  'towers.towers[].key': 'partial',
  'towers.towers[].name': 'open',
  'towers.towers[].soul': 'checked',
  'towers.towers[].terrain.auraType': 'checked',
  'towers.towers[].terrain.kind': 'open',
  'towers.towers[].upgrades.note': 'open',
  'towers.towers[].upgrades.specials[].key': 'checked',
  'towers.towers[].upgrades.specials[].note': 'open',
  'towers.towers[].upgrades.specials[].type': 'checked',
  'tree.nodes[].branch': 'open',
  'tree.nodes[].desc': 'open',
  'tree.nodes[].key': 'open',
  'tree.nodes[].kind': 'checked',
  'tree.nodes[].name': 'open',
  'waves.waves[].groups[].enemy': 'checked',
  'weapons.awakenings[].boon': 'checked',
  'weapons.awakenings[].desc': 'open',
  'weapons.awakenings[].key': 'open',
  'weapons.awakenings[].name': 'open',
  'weapons.awakenings[].weapon': 'checked',
  'weapons.weapons[].desc': 'open',
  'weapons.weapons[].key': 'partial',
  'weapons.weapons[].kind': 'checked',
  'weapons.weapons[].name': 'open',
  'weapons.weapons[].source': 'checked',
};
